# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my/my.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='my/my.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bmy/my.proto\"r\n\nParamValue\x12\x15\n\x0b\x64ouble_name\x18\x01 \x01(\x01H\x00\x12\x12\n\x08int_name\x18\x02 \x01(\x03H\x00\x12\x13\n\tbool_name\x18\x03 \x01(\x08H\x00\x12\x15\n\x0bstring_name\x18\x04 \x01(\tH\x00\x42\r\n\x0bvalue_oneof\"\xca\x01\n\x0cSellerParams\x12\"\n\x06result\x18\x01 \x03(\x0b\x32\x12.SellerParams.Item\x1a\x95\x01\n\x04Item\x12\x11\n\tseller_id\x18\x01 \x01(\x03\x12\x0e\n\x06rating\x18\x02 \x01(\x01\x12.\n\x06params\x18\x03 \x03(\x0b\x32\x1e.SellerParams.Item.ParamsEntry\x1a:\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.ParamValue:\x02\x38\x01\x62\x06proto3')
)




_PARAMVALUE = _descriptor.Descriptor(
  name='ParamValue',
  full_name='ParamValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='double_name', full_name='ParamValue.double_name', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_name', full_name='ParamValue.int_name', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_name', full_name='ParamValue.bool_name', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_name', full_name='ParamValue.string_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value_oneof', full_name='ParamValue.value_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=15,
  serialized_end=129,
)


_SELLERPARAMS_ITEM_PARAMSENTRY = _descriptor.Descriptor(
  name='ParamsEntry',
  full_name='SellerParams.Item.ParamsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='SellerParams.Item.ParamsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='SellerParams.Item.ParamsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=334,
)

_SELLERPARAMS_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='SellerParams.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seller_id', full_name='SellerParams.Item.seller_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='SellerParams.Item.rating', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='SellerParams.Item.params', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SELLERPARAMS_ITEM_PARAMSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=334,
)

_SELLERPARAMS = _descriptor.Descriptor(
  name='SellerParams',
  full_name='SellerParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='SellerParams.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SELLERPARAMS_ITEM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=334,
)

_PARAMVALUE.oneofs_by_name['value_oneof'].fields.append(
  _PARAMVALUE.fields_by_name['double_name'])
_PARAMVALUE.fields_by_name['double_name'].containing_oneof = _PARAMVALUE.oneofs_by_name['value_oneof']
_PARAMVALUE.oneofs_by_name['value_oneof'].fields.append(
  _PARAMVALUE.fields_by_name['int_name'])
_PARAMVALUE.fields_by_name['int_name'].containing_oneof = _PARAMVALUE.oneofs_by_name['value_oneof']
_PARAMVALUE.oneofs_by_name['value_oneof'].fields.append(
  _PARAMVALUE.fields_by_name['bool_name'])
_PARAMVALUE.fields_by_name['bool_name'].containing_oneof = _PARAMVALUE.oneofs_by_name['value_oneof']
_PARAMVALUE.oneofs_by_name['value_oneof'].fields.append(
  _PARAMVALUE.fields_by_name['string_name'])
_PARAMVALUE.fields_by_name['string_name'].containing_oneof = _PARAMVALUE.oneofs_by_name['value_oneof']
_SELLERPARAMS_ITEM_PARAMSENTRY.fields_by_name['value'].message_type = _PARAMVALUE
_SELLERPARAMS_ITEM_PARAMSENTRY.containing_type = _SELLERPARAMS_ITEM
_SELLERPARAMS_ITEM.fields_by_name['params'].message_type = _SELLERPARAMS_ITEM_PARAMSENTRY
_SELLERPARAMS_ITEM.containing_type = _SELLERPARAMS
_SELLERPARAMS.fields_by_name['result'].message_type = _SELLERPARAMS_ITEM
DESCRIPTOR.message_types_by_name['ParamValue'] = _PARAMVALUE
DESCRIPTOR.message_types_by_name['SellerParams'] = _SELLERPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParamValue = _reflection.GeneratedProtocolMessageType('ParamValue', (_message.Message,), dict(
  DESCRIPTOR = _PARAMVALUE,
  __module__ = 'my.my_pb2'
  # @@protoc_insertion_point(class_scope:ParamValue)
  ))
_sym_db.RegisterMessage(ParamValue)

SellerParams = _reflection.GeneratedProtocolMessageType('SellerParams', (_message.Message,), dict(

  Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(

    ParamsEntry = _reflection.GeneratedProtocolMessageType('ParamsEntry', (_message.Message,), dict(
      DESCRIPTOR = _SELLERPARAMS_ITEM_PARAMSENTRY,
      __module__ = 'my.my_pb2'
      # @@protoc_insertion_point(class_scope:SellerParams.Item.ParamsEntry)
      ))
    ,
    DESCRIPTOR = _SELLERPARAMS_ITEM,
    __module__ = 'my.my_pb2'
    # @@protoc_insertion_point(class_scope:SellerParams.Item)
    ))
  ,
  DESCRIPTOR = _SELLERPARAMS,
  __module__ = 'my.my_pb2'
  # @@protoc_insertion_point(class_scope:SellerParams)
  ))
_sym_db.RegisterMessage(SellerParams)
_sym_db.RegisterMessage(SellerParams.Item)
_sym_db.RegisterMessage(SellerParams.Item.ParamsEntry)


_SELLERPARAMS_ITEM_PARAMSENTRY._options = None
# @@protoc_insertion_point(module_scope)
